services:
    yacare.comercio.comercio_listener:
        class: Yacare\ComercioBundle\EventListener\ComercioListener
        arguments: [ '@service_container' ]
        public:  false
        tags:
            - { name: doctrine.event_subscriber }
