@startuml

!include ../../Tapir/Base/UC_skinparam.skp

/'CASOS DE USO'/
(ACO1 - Registrar actividad) as ACO1
(ACO2 - Suprimir actividad) as ACO2
(ACO3 - Modificar actividad) as ACO3
(ACO4 - Consultar actividad) as ACO4
(ACO5 - Listar actividad) as ACO5

/'ACTORES'/
:Usuario autenticado: as actor1

/'RELACIONES'/
actor1 -up- ACO1
actor1 -l- ACO2
actor1 -- ACO3
actor1 -r- ACO4
actor1 -- ACO5

ACO4 ..> ACO2 : extend
ACO3 <.. ACO4 : extend
ACO5 ..> ACO2 : extend
ACO3 <.. ACO5 : extend

@enduml
