@startuml

namespace Yacare.AdministracionBundle.Entity  {
	class Expediente <<class>> {		
	}
}

!include /%HOME%/%YACARE_DIR%/docs/Clases/Tapir/Base/DC_TraitsCollection.pu!0
!include /%HOME%/%YACARE_DIR%/docs/Clases/Tapir/Base/DC_TraitsCollection.pu!5

Yacare.AdministracionBundle.Entity.Expediente--> Tapir.BaseBundle.Entity.ConId: Implementa
Yacare.AdministracionBundle.Entity.Expediente--> Tapir.BaseBundle.Entity.ConNombre: Implementa

@enduml
