@startuml

title Administracion/<b>Traits Collection</b>\n

package Yacare.AdministracionBundle.Entity {
	class ConExpediente <<(T,#FF7700) trait>> {
  		#ExpedienteNumero
  		getExpedienteNumero()
  		setExpedienteNumero($ExpedienteNumero)
	}
}
 
@enduml


@startuml

package Yacare.Administracion {
	class ConActoAdministrativo <<(T,#FF7700) trait>> {
  		#ActoAdministrativoNumero
  		getActoAdministrativoNumero()
  		setActoadministrativoNumero()
 	}
}

@enduml
