imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.yml }
    - { resource: config_app.yml }
    - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: [ 'TapirTemplateBundle:Form:bootstrap_3_horizontal_layout.html.twig' ]

# Doctrine Configuration
doctrine:
    dbal:
        types:
            geometry:   CrEOF\Spatial\DBAL\Types\GeometryType
            point:      CrEOF\Spatial\DBAL\Types\Geometry\PointType
            polygon:    CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
            linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                # if using pdo_sqlite as your database driver, add the path in parameters.yml
                # e.g. database_path: "%kernel.root_dir%/data/data.db3"
                # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        #auto_mapping: true
        default_entity_manager: default
        entity_managers:
            default:
                dql:
                    string_functions:
                        MONTH: Tapir\BaseBundle\DQL\Month
                        YEAR: Tapir\BaseBundle\DQL\Year
                    numeric_functions:
                        st_contains:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STContains
                        st_distance:     CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
                        st_area:         CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STArea
                        st_length:       CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STLength
                        st_geomfromtext: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeomFromText
                connection: default
                mappings:
                    TapirBaseBundle:  ~
                    TapirAnnotationBundle: ~
                    YacareBaseBundle: ~
                    YacareComprasBundle: ~
                    YacareCatastroBundle: ~
                    YacareComercioBundle: ~
                    YacareAdministracionBundle: ~
                    YacareInspeccionBundle: ~
                    YacareMunirgBundle: ~
                    YacareObrasParticularesBundle: ~
                    YacareOrganizacionBundle: ~
                    YacareRecursosHumanosBundle: ~
                    YacareTramitesBundle: ~
                    YacareRequerimientosBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


jms_security_extra:
    # Enabling this setting will add an additional special attribute "ROLE_IDDQD".
    # Anybody with this attribute will effectively bypass all security checks.
    enable_iddqd_attribute: true
    # Enables expression language
    expressions: true

knp_paginator:
    page_range: 10                     # default page range used in pagination control
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig

knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf
        options:
            - { name: page-size, value: A4 }
            - { name: lowquality, value: false }
            - { name: quiet, value: true }
            - { name: disable-javascript, value: true }
            - { name: print-media-type, value: true }
            - { name: image-quality, value 80 }
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage
        options:
            - { name: page-size, value: A4 }
            - { name: lowquality, value: false }
            - { name: quiet, value: true }
            - { name: disable-javascript, value: true }
            - { name: print-media-type, value: true }
            - { name: image-quality, value 80 }

liip_imagine:
    filter_sets:
        thumb256:
            quality: 60
            filters:
                thumbnail: { size: [256, 256], mode: outbound }
                
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
        - { name: twig.extension }
