security:
    access_denied_url: /base/accesodenegado
    role_hierarchy:
        ROLE_ADMINISTRADOR: ROLE_USUARIO
        ROLE_SUPER_ADMIN: [ROLE_USUARIO, ROLE_ADMINISTRADOR, ROLE_ALLOWED_TO_SWITCH]

    providers:
        personas:
            # Usuarios de la tabla de personas
            entity: { class: "YacareBaseBundle:Persona", property: Username }
        in_memory:
            # Usuarios adicionales para pruebas unitarias
            memory:
                users:
                    # Este rol se convierte en administrador en config_test.yml
                    pruebas: { password: pruebas, roles: [ ROLE_PRUEBAS ] }
    encoders:
        Yacare\BaseBundle\Entity\Persona:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        cssjs:
            pattern:  ^%web_root%/bundles/(yacare|tapir)base|tapirtemplate/(css|js|fonts|images|img)/
            security: false
            
        formingreso:
            pattern:    ^/login$
            anonymous:  ~

        # El área segura se autentica mediante formulario
        areasegura:
            pattern:    ^/.*
            form_login:
                login_path:  /login
                check_path:  /login_check
                remember_me: true
            logout:
                path:   /logout
                target: /
                invalidate_session: true
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /.*
                domain:   ~
            security: true
            anonymous: true

        # áreas públicas (sin autenticación)            
        yacare_requerimientos_requerimiento_anonimo:
            pattern:  ^/requerimientos/requerimiento/anonimo/
            security: false

    access_control:
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: ^/munirg/ldap/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/requerimientos/requerimiento/anonimo/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pub, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, roles: ROLE_USUARIO }
        - { path: /base, roles: ROLE_ADMINISTRADOR }
        - { path: /comercio, roles: ROLE_COMERCIO }
        - { path: /compras, roles: ROLE_COMPRAS }
        - { path: /inspeccion, roles: ROLE_INSPECCION }
        - { path: /tramites, roles: ROLE_TRAMITES }
        - { path: /requerimientos/categoria, roles: ROLE_REQUERIMIENTOS_ADMINISTRADOR }

