services:
    yacare.tramites.tramite_listener:
        class: Yacare\TramitesBundle\EventListener\TramiteListener
        arguments: [ '@service_container' ]
        public:  false
        tags:
            - { name: doctrine.event_subscriber }
