<disabled-script type="text/javascript" src="../js/jquery-2.1.0.min.js"></disabled-script>
<disabled-script type="text/javascript" src="../js/jquery-ui-1.10.4.custom.min.js"></disabled-script>
<disabled-script type="text/javascript" src="../js/jquery.ui.datepicker-es.js"></disabled-script>
<disabled-script type="text/javascript" src="../js/bootstrap.min.js"></disabled-script>
<disabled-script type="text/javascript" src="../js/jquery.history.js"></disabled-script>
