@startuml
namespace Tapir.BaseBundle.Entity  {
	class PersonaRol << class >> {
	-Nombre
	-Codigo
	#Personas
	+getNombre()
	+getRole()
	+setNombre()
	+getCodigo()
	+setCodigo()
	+__toString()
	}		
}
!include DC_TraitsCollection.iuml!0
Tapir.BaseBundle.Entity.PersonaRol-->Tapir.BaseBundle.ConId
@enduml
