@startuml

namespace Tapir.BaseBundle.Entity <<cloud>> {

	class ConId <<(T,#FF7700) trait>> {
 		+id
	}
 
	class ConIdMetodos <<(T,#FF7700) trait>> {
		+getId()
		+setId($id)
		+getYri64()
		+getYri()
		+getDamm()
		+getYriQrBase64()
	}
	ConId -l- ConIdMetodos
}
 
@enduml


@startuml

namespace Tapir.BaseBundle.Entity<<cloud>> {
	class Versionable <<(T,#FF7700) trait>> {
		-Version
		+getVersion()
		+setVersion()
	}
	
	class Auditable <<(T,#FF7700) trait>> {
	}
	
	Versionable .l.|> Auditable : implementa
} 

@enduml


@startuml

namespace Tapir.BaseBundle.Entity <<cloud>> {
	class Suprimible <<(T,#FF7700) trait>> {
		-Suprimido
		+Suprimir()
	}
}
 
@enduml


@startuml

namespace Tapir.BaseBundle.Entity <<cloud>>{
	class Archivable <<(T,#FF7700) trait>> {
		-Archivado
		+Archivar()
	}
}
 
@enduml


@startuml

namespace Tapir.BaseBundle.Entity <<cloud>> {
	class ConObs <<(T,#FF7700) trait>> {
		+Observaciones
		+getObs()
		+setObs()
	}
}
 
@enduml


@startuml
 
namespace Tapir.BaseBundle.Entity <<cloud>>{
	class ConNombre <<(T,#FF7700) trait>>{
		+Nombre
		+__toString()
		+getetNombre()
		+setNombre()
	}
}
 
@enduml
