@startuml

!include ../../Tapir/Base/UC_skinparam.skp

/'CASOS DE USO'/
(ARH6 - Registrar agente_grupo) as ARH6
(ARH7 - Suprimir agente_grupo) as ARH7
(ARH8 - Modificar agente_grupo) as ARH8
(ARH9 - Consultar agente_grupo) as ARH9
(ARH10 - Listar agente_grupo) as ARH10

/'ACTORES'/
:Usuario autenticado: as actor1

/'RELACIONES'/
actor1 -up- ARH6
actor1 -l- ARH7
actor1 -- ARH8
actor1 -r- ARH9
actor1 -- ARH10

ARH9 ..> ARH7 : extend
ARH8 <.. ARH9 : extend
ARH10 ..> ARH7 : extend
ARH8 <.. ARH10 : extend

@enduml
