@startuml

!include ../../Tapir/Base/UC_skinparam.skp

/'CASOS DE USO'/
(ARH1 - Registrar agente) as ARH1
(ARH2 - Suprimir agente) as ARH2
(ARH3 - Modificar agente) as ARH3
(ARH4 - Consultar agente) as ARH4
(ARH5 - Listar agente) as ARH5

/'ACTORES'/
:Usuario autenticado: as actor1

/'RELACIONES'/
actor1 -up- ARH1
actor1 -l- ARH2
actor1 -- ARH3
actor1 -r- ARH4
actor1 -- ARH5

ARH4 ..> ARH2 : extend
ARH3 <.. ARH4 : extend
ARH5 ..> ARH2 : extend
ARH3 <.. ARH5 : extend

@enduml
