@startuml

!include /%home%/%yacare_root_dir%/%puml_root_dir%/Tapir/Base/UC_skinparam.skp

/'CASOS DE USO'/
(ARH1- Registrar departamento) as ARH1
(ARH2 - Suprimir departamento) as ARH2
(ARH3 - Modificar departamento) as ARH3
(ARH4 - Consultar departamento) as ARH4
(ARH5 - Listar departamento) as ARH5

/'ACTORES'/
:Usuario autenticado: as actor1

/'RELACIONES'/
actor1 -up- ARH1
actor1 -l- ARH2
actor1 -- ARH3
actor1 -r- ARH4
actor1 -- ARH5

ARH4 ..> ARH2 : extend
ARH3 <.. ARH4 : extend
ARH5 ..> ARH2 : extend
ARH3 <.. ARH5 : extend

@enduml
