@startuml

!include ../../Tapir/Base/UC_skinparam.skp

/'CASOS DE USO'/
(ARH11 - Registrar departamento) as ARH11
(ARH12 - Suprimir departamento) as ARH12
(ARH13 - Modificar departamento) as ARH13
(ARH14 - Consultar departamento) as ARH14
(ARH15 - Listar departamento) as ARH15

/'ACTORES'/
:Usuario autenticado: as actor1

/'RELACIONES'/
actor1 -up- ARH11
actor1 -l- ARH12
actor1 -- ARH13
actor1 -r- ARH14
actor1 -- ARH15

ARH14 ..> ARH12 : extend
ARH13 <.. ARH14 : extend
ARH15 ..> ARH12 : extend
ARH13 <.. ARH15 : extend

@enduml
