services:
    tapir.base_bundle.auditable_listener:
        class: Tapir\BaseBundle\ORM\Auditable\AuditableListener
        arguments: [ '@service_container' ]
        public:  false
        tags:
          - { name: doctrine.event_subscriber }
            
    tapirbasebundle.twig.tapir_extension:
        class: Tapir\BaseBundle\Twig\TapirExtension
        tags:
          - { name: twig.extension }
        
    tapirbasebundle.twig.tapir_formatextension:
        class: Tapir\BaseBundle\Twig\FormatExtension
        tags:
          - { name: twig.extension }
        
    app.form.type.buttongroup:
        class: Tapir\BaseBundle\Form\Type\ButtonGroupType
        tags:
          - { name: form.type, alias: buttongroup }
    
    audit.logger:
        class:     Symfony\Bridge\Monolog\Logger
        arguments: [ app ]
        calls:
            - [ pushHandler, [ '@audit.logger_handler' ] ]
    
    audit.logger_handler:
        class:     Monolog\Handler\StreamHandler       
        arguments: [ '%kernel.logs_dir%/audit.log', 200 ]
