@startuml
namespace Yacare.BaseBundle.Entity <<cloud>> {
	class ConDomicilio << (T,#FF7700) trait >> {
		+DomicilioCalle
		+DomicilioCalleNombre
		+DomicilioNumero
		+DomicilioPiso
		+DomicilioPuerta
		+getDomicilio()
	}	
	class ConPartida << (T,#FF7700) trait >> {
		+Partida
	}
	
}
!include /home/alediaz/workspace/Yacare1/docs/Clases/Yacaré/Catastro/DC_Entidades.pu

@enduml

