parameters:
  tapir_controls.twig_extension.class: Tapir\TemplateBundle\Twig\ControlsExtension

services:
  tapir_controls.twig.tabs_extension:
    class: '%tapir_controls.twig_extension.class%'
    tags:
        - { name: twig.extension }
    
  # email type
  email.type:
      class: Tapir\TemplateBundle\Form\Type\EmailType
      tags:
          - { name: form.type, alias: email }