@startuml
namespace Yacare.ComercioBundle.Helper  {
	class EstadoRequisitoHelper << class >> {
	}
	class TramiteHabilitacionComercialHelper << class >> {
		+EmitirComprobante(){redefine}
		+Consultar()
	}
}
@enduml

